### PR TITLE
fix #318 locale is not working for calendar Read

### LINKED ISSUE #318: Locale option is not working in Calendar parsing
When I was trying to create a customized calendar read with `calendarRead ` function it was not working as expected. Looks like the argument `locale` is not used here

https://github.com/scopt/scopt/blob/34548cf739fee1cecd7daf056a3b334cf4d68022/jvm/src/main/scala/PlatformReadInstances.scala#L19-L25

### PR DESCRIPTION
**Pull request by fangpings**
This PR fixes #318

### CODE REVIEW

File: jvm/src/main/scala/PlatformReadInstances.scala [hunk 1]
```diff
@@ -16,10 +17,11 @@ private[scopt] object platform {
   def mkParseEx(s: String, p: Int) = new java.text.ParseException(s, p)
 
   trait PlatformReadInstances {
-    def calendarRead(pattern: String): Read[Calendar] = calendarRead(pattern, Locale.getDefault)
-    def calendarRead(pattern: String, locale: Locale): Read[Calendar] =
+    def calendarRead(pattern: String): Read[Calendar] = calendarRead(pattern, TimeZone.getDefault)
+    def calendarRead(pattern: String, timeZone: TimeZone): Read[Calendar] =
```
Comment (eed3si9n) [inline jvm/src/main/scala/PlatformReadInstances.scala]: I think this is going to break the binary compatibility, so I'm guessing we can't do that.

**Review by eed3si9n — APPROVED** [review]
